// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Authentication.proto

package com.wisegeek.finance.protobuf;


public final class Authentication {
  private Authentication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AuthenticationRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string LoginName = 1;
    /**
     * <code>required string LoginName = 1;</code>
     */
    boolean hasLoginName();
    /**
     * <code>required string LoginName = 1;</code>
     */
    java.lang.String getLoginName();
    /**
     * <code>required string LoginName = 1;</code>
     */
    com.google.protobuf.ByteString
        getLoginNameBytes();

    // required string Password = 2;
    /**
     * <code>required string Password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string Password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string Password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // optional .com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup Group = 3 [default = GUEST];
    /**
     * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup Group = 3 [default = GUEST];</code>
     */
    boolean hasGroup();
    /**
     * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup Group = 3 [default = GUEST];</code>
     */
    com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup getGroup();

    // optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;
    /**
     * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
     */
    boolean hasTerminal();
    /**
     * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
     */
    com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo getTerminal();
    /**
     * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
     */
    com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfoOrBuilder getTerminalOrBuilder();
  }
  /**
   * Protobuf type {@code com.wisegeek.finance.protobuf.AuthenticationRequest}
   */
  public static final class AuthenticationRequest extends
      com.google.protobuf.GeneratedMessage
      implements AuthenticationRequestOrBuilder {
    // Use AuthenticationRequest.newBuilder() to construct.
    private AuthenticationRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AuthenticationRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AuthenticationRequest defaultInstance;
    public static AuthenticationRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AuthenticationRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AuthenticationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              loginName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup value = com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                group_ = value;
              }
              break;
            }
            case 34: {
              com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = terminal_.toBuilder();
              }
              terminal_ = input.readMessage(com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(terminal_);
                terminal_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.class, com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AuthenticationRequest> PARSER =
        new com.google.protobuf.AbstractParser<AuthenticationRequest>() {
      public AuthenticationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthenticationRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AuthenticationRequest> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup}
     */
    public enum UserGroup
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GUEST = 0;</code>
       */
      GUEST(0, 0),
      /**
       * <code>GENERAL = 1;</code>
       */
      GENERAL(1, 1),
      /**
       * <code>VIP = 2;</code>
       */
      VIP(2, 2),
      /**
       * <code>TEST = 3;</code>
       */
      TEST(3, 3),
      ;

      /**
       * <code>GUEST = 0;</code>
       */
      public static final int GUEST_VALUE = 0;
      /**
       * <code>GENERAL = 1;</code>
       */
      public static final int GENERAL_VALUE = 1;
      /**
       * <code>VIP = 2;</code>
       */
      public static final int VIP_VALUE = 2;
      /**
       * <code>TEST = 3;</code>
       */
      public static final int TEST_VALUE = 3;


      public final int getNumber() { return value; }

      public static UserGroup valueOf(int value) {
        switch (value) {
          case 0: return GUEST;
          case 1: return GENERAL;
          case 2: return VIP;
          case 3: return TEST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<UserGroup>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<UserGroup>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<UserGroup>() {
              public UserGroup findValueByNumber(int number) {
                return UserGroup.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final UserGroup[] VALUES = values();

      public static UserGroup valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private UserGroup(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup)
    }

    public interface TerminalInfoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string MachineType = 1;
      /**
       * <code>required string MachineType = 1;</code>
       */
      boolean hasMachineType();
      /**
       * <code>required string MachineType = 1;</code>
       */
      java.lang.String getMachineType();
      /**
       * <code>required string MachineType = 1;</code>
       */
      com.google.protobuf.ByteString
          getMachineTypeBytes();

      // optional string Version = 2;
      /**
       * <code>optional string Version = 2;</code>
       */
      boolean hasVersion();
      /**
       * <code>optional string Version = 2;</code>
       */
      java.lang.String getVersion();
      /**
       * <code>optional string Version = 2;</code>
       */
      com.google.protobuf.ByteString
          getVersionBytes();
    }
    /**
     * Protobuf type {@code com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo}
     */
    public static final class TerminalInfo extends
        com.google.protobuf.GeneratedMessage
        implements TerminalInfoOrBuilder {
      // Use TerminalInfo.newBuilder() to construct.
      private TerminalInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private TerminalInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final TerminalInfo defaultInstance;
      public static TerminalInfo getDefaultInstance() {
        return defaultInstance;
      }

      public TerminalInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private TerminalInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                machineType_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                version_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_TerminalInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_TerminalInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.class, com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<TerminalInfo> PARSER =
          new com.google.protobuf.AbstractParser<TerminalInfo>() {
        public TerminalInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new TerminalInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<TerminalInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string MachineType = 1;
      public static final int MACHINETYPE_FIELD_NUMBER = 1;
      private java.lang.Object machineType_;
      /**
       * <code>required string MachineType = 1;</code>
       */
      public boolean hasMachineType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string MachineType = 1;</code>
       */
      public java.lang.String getMachineType() {
        java.lang.Object ref = machineType_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            machineType_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string MachineType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMachineTypeBytes() {
        java.lang.Object ref = machineType_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          machineType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string Version = 2;
      public static final int VERSION_FIELD_NUMBER = 2;
      private java.lang.Object version_;
      /**
       * <code>optional string Version = 2;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string Version = 2;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string Version = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        machineType_ = "";
        version_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasMachineType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getMachineTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getVersionBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getMachineTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getVersionBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_TerminalInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_TerminalInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.class, com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.Builder.class);
        }

        // Construct using com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          machineType_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          version_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_TerminalInfo_descriptor;
        }

        public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo getDefaultInstanceForType() {
          return com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.getDefaultInstance();
        }

        public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo build() {
          com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo buildPartial() {
          com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo result = new com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.machineType_ = machineType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.version_ = version_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo) {
            return mergeFrom((com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo other) {
          if (other == com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.getDefaultInstance()) return this;
          if (other.hasMachineType()) {
            bitField0_ |= 0x00000001;
            machineType_ = other.machineType_;
            onChanged();
          }
          if (other.hasVersion()) {
            bitField0_ |= 0x00000002;
            version_ = other.version_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasMachineType()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string MachineType = 1;
        private java.lang.Object machineType_ = "";
        /**
         * <code>required string MachineType = 1;</code>
         */
        public boolean hasMachineType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string MachineType = 1;</code>
         */
        public java.lang.String getMachineType() {
          java.lang.Object ref = machineType_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            machineType_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string MachineType = 1;</code>
         */
        public com.google.protobuf.ByteString
            getMachineTypeBytes() {
          java.lang.Object ref = machineType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            machineType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string MachineType = 1;</code>
         */
        public Builder setMachineType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          machineType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string MachineType = 1;</code>
         */
        public Builder clearMachineType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          machineType_ = getDefaultInstance().getMachineType();
          onChanged();
          return this;
        }
        /**
         * <code>required string MachineType = 1;</code>
         */
        public Builder setMachineTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          machineType_ = value;
          onChanged();
          return this;
        }

        // optional string Version = 2;
        private java.lang.Object version_ = "";
        /**
         * <code>optional string Version = 2;</code>
         */
        public boolean hasVersion() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string Version = 2;</code>
         */
        public java.lang.String getVersion() {
          java.lang.Object ref = version_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            version_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string Version = 2;</code>
         */
        public com.google.protobuf.ByteString
            getVersionBytes() {
          java.lang.Object ref = version_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            version_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string Version = 2;</code>
         */
        public Builder setVersion(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          version_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string Version = 2;</code>
         */
        public Builder clearVersion() {
          bitField0_ = (bitField0_ & ~0x00000002);
          version_ = getDefaultInstance().getVersion();
          onChanged();
          return this;
        }
        /**
         * <code>optional string Version = 2;</code>
         */
        public Builder setVersionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          version_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo)
      }

      static {
        defaultInstance = new TerminalInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo)
    }

    private int bitField0_;
    // required string LoginName = 1;
    public static final int LOGINNAME_FIELD_NUMBER = 1;
    private java.lang.Object loginName_;
    /**
     * <code>required string LoginName = 1;</code>
     */
    public boolean hasLoginName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string LoginName = 1;</code>
     */
    public java.lang.String getLoginName() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string LoginName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLoginNameBytes() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string Password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string Password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup Group = 3 [default = GUEST];
    public static final int GROUP_FIELD_NUMBER = 3;
    private com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup group_;
    /**
     * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup Group = 3 [default = GUEST];</code>
     */
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup Group = 3 [default = GUEST];</code>
     */
    public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup getGroup() {
      return group_;
    }

    // optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;
    public static final int TERMINAL_FIELD_NUMBER = 4;
    private com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo terminal_;
    /**
     * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
     */
    public boolean hasTerminal() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
     */
    public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo getTerminal() {
      return terminal_;
    }
    /**
     * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
     */
    public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfoOrBuilder getTerminalOrBuilder() {
      return terminal_;
    }

    private void initFields() {
      loginName_ = "";
      password_ = "";
      group_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup.GUEST;
      terminal_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLoginName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasTerminal()) {
        if (!getTerminal().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLoginNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, group_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, terminal_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLoginNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, group_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, terminal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wisegeek.finance.protobuf.AuthenticationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wisegeek.finance.protobuf.Authentication.AuthenticationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.class, com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.Builder.class);
      }

      // Construct using com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTerminalFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        loginName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        group_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup.GUEST;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (terminalBuilder_ == null) {
          terminal_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.getDefaultInstance();
        } else {
          terminalBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_descriptor;
      }

      public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest getDefaultInstanceForType() {
        return com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.getDefaultInstance();
      }

      public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest build() {
        com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest buildPartial() {
        com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest result = new com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loginName_ = loginName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.group_ = group_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (terminalBuilder_ == null) {
          result.terminal_ = terminal_;
        } else {
          result.terminal_ = terminalBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest) {
          return mergeFrom((com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest other) {
        if (other == com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.getDefaultInstance()) return this;
        if (other.hasLoginName()) {
          bitField0_ |= 0x00000001;
          loginName_ = other.loginName_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasGroup()) {
          setGroup(other.getGroup());
        }
        if (other.hasTerminal()) {
          mergeTerminal(other.getTerminal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLoginName()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        if (hasTerminal()) {
          if (!getTerminal().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string LoginName = 1;
      private java.lang.Object loginName_ = "";
      /**
       * <code>required string LoginName = 1;</code>
       */
      public boolean hasLoginName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string LoginName = 1;</code>
       */
      public java.lang.String getLoginName() {
        java.lang.Object ref = loginName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          loginName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string LoginName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLoginNameBytes() {
        java.lang.Object ref = loginName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string LoginName = 1;</code>
       */
      public Builder setLoginName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        loginName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string LoginName = 1;</code>
       */
      public Builder clearLoginName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loginName_ = getDefaultInstance().getLoginName();
        onChanged();
        return this;
      }
      /**
       * <code>required string LoginName = 1;</code>
       */
      public Builder setLoginNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        loginName_ = value;
        onChanged();
        return this;
      }

      // required string Password = 2;
      private java.lang.Object password_ = "";
      /**
       * <code>required string Password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string Password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string Password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // optional .com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup Group = 3 [default = GUEST];
      private com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup group_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup.GUEST;
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup Group = 3 [default = GUEST];</code>
       */
      public boolean hasGroup() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup Group = 3 [default = GUEST];</code>
       */
      public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup getGroup() {
        return group_;
      }
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup Group = 3 [default = GUEST];</code>
       */
      public Builder setGroup(com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.UserGroup Group = 3 [default = GUEST];</code>
       */
      public Builder clearGroup() {
        bitField0_ = (bitField0_ & ~0x00000004);
        group_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.UserGroup.GUEST;
        onChanged();
        return this;
      }

      // optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;
      private com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo terminal_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo, com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.Builder, com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfoOrBuilder> terminalBuilder_;
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
       */
      public boolean hasTerminal() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
       */
      public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo getTerminal() {
        if (terminalBuilder_ == null) {
          return terminal_;
        } else {
          return terminalBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
       */
      public Builder setTerminal(com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo value) {
        if (terminalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          terminal_ = value;
          onChanged();
        } else {
          terminalBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
       */
      public Builder setTerminal(
          com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.Builder builderForValue) {
        if (terminalBuilder_ == null) {
          terminal_ = builderForValue.build();
          onChanged();
        } else {
          terminalBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
       */
      public Builder mergeTerminal(com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo value) {
        if (terminalBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              terminal_ != com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.getDefaultInstance()) {
            terminal_ =
              com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.newBuilder(terminal_).mergeFrom(value).buildPartial();
          } else {
            terminal_ = value;
          }
          onChanged();
        } else {
          terminalBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
       */
      public Builder clearTerminal() {
        if (terminalBuilder_ == null) {
          terminal_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.getDefaultInstance();
          onChanged();
        } else {
          terminalBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
       */
      public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.Builder getTerminalBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getTerminalFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
       */
      public com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfoOrBuilder getTerminalOrBuilder() {
        if (terminalBuilder_ != null) {
          return terminalBuilder_.getMessageOrBuilder();
        } else {
          return terminal_;
        }
      }
      /**
       * <code>optional .com.wisegeek.finance.protobuf.AuthenticationRequest.TerminalInfo Terminal = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo, com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.Builder, com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfoOrBuilder> 
          getTerminalFieldBuilder() {
        if (terminalBuilder_ == null) {
          terminalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo, com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfo.Builder, com.wisegeek.finance.protobuf.Authentication.AuthenticationRequest.TerminalInfoOrBuilder>(
                  terminal_,
                  getParentForChildren(),
                  isClean());
          terminal_ = null;
        }
        return terminalBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.wisegeek.finance.protobuf.AuthenticationRequest)
    }

    static {
      defaultInstance = new AuthenticationRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wisegeek.finance.protobuf.AuthenticationRequest)
  }

  public interface AuthenticationResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType AuthResult = 1;
    /**
     * <code>required .com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType AuthResult = 1;</code>
     */
    boolean hasAuthResult();
    /**
     * <code>required .com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType AuthResult = 1;</code>
     */
    com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType getAuthResult();

    // optional string AuthMsg = 2;
    /**
     * <code>optional string AuthMsg = 2;</code>
     */
    boolean hasAuthMsg();
    /**
     * <code>optional string AuthMsg = 2;</code>
     */
    java.lang.String getAuthMsg();
    /**
     * <code>optional string AuthMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getAuthMsgBytes();

    // optional fixed64 SessionID = 3;
    /**
     * <code>optional fixed64 SessionID = 3;</code>
     */
    boolean hasSessionID();
    /**
     * <code>optional fixed64 SessionID = 3;</code>
     */
    long getSessionID();
  }
  /**
   * Protobuf type {@code com.wisegeek.finance.protobuf.AuthenticationResponse}
   */
  public static final class AuthenticationResponse extends
      com.google.protobuf.GeneratedMessage
      implements AuthenticationResponseOrBuilder {
    // Use AuthenticationResponse.newBuilder() to construct.
    private AuthenticationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AuthenticationResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AuthenticationResponse defaultInstance;
    public static AuthenticationResponse getDefaultInstance() {
      return defaultInstance;
    }

    public AuthenticationResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AuthenticationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType value = com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                authResult_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              authMsg_ = input.readBytes();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              sessionID_ = input.readFixed64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.class, com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<AuthenticationResponse> PARSER =
        new com.google.protobuf.AbstractParser<AuthenticationResponse>() {
      public AuthenticationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthenticationResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AuthenticationResponse> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType}
     */
    public enum AuthResultType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LoginSucceeded = 0;</code>
       */
      LoginSucceeded(0, 0),
      /**
       * <code>WrongPasswordAccountNotExist = 1;</code>
       */
      WrongPasswordAccountNotExist(1, 1),
      /**
       * <code>ServerBusy = 2;</code>
       */
      ServerBusy(2, 2),
      /**
       * <code>UserLocking = 3;</code>
       */
      UserLocking(3, 3),
      ;

      /**
       * <code>LoginSucceeded = 0;</code>
       */
      public static final int LoginSucceeded_VALUE = 0;
      /**
       * <code>WrongPasswordAccountNotExist = 1;</code>
       */
      public static final int WrongPasswordAccountNotExist_VALUE = 1;
      /**
       * <code>ServerBusy = 2;</code>
       */
      public static final int ServerBusy_VALUE = 2;
      /**
       * <code>UserLocking = 3;</code>
       */
      public static final int UserLocking_VALUE = 3;


      public final int getNumber() { return value; }

      public static AuthResultType valueOf(int value) {
        switch (value) {
          case 0: return LoginSucceeded;
          case 1: return WrongPasswordAccountNotExist;
          case 2: return ServerBusy;
          case 3: return UserLocking;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AuthResultType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<AuthResultType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AuthResultType>() {
              public AuthResultType findValueByNumber(int number) {
                return AuthResultType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final AuthResultType[] VALUES = values();

      public static AuthResultType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private AuthResultType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType)
    }

    private int bitField0_;
    // required .com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType AuthResult = 1;
    public static final int AUTHRESULT_FIELD_NUMBER = 1;
    private com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType authResult_;
    /**
     * <code>required .com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType AuthResult = 1;</code>
     */
    public boolean hasAuthResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType AuthResult = 1;</code>
     */
    public com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType getAuthResult() {
      return authResult_;
    }

    // optional string AuthMsg = 2;
    public static final int AUTHMSG_FIELD_NUMBER = 2;
    private java.lang.Object authMsg_;
    /**
     * <code>optional string AuthMsg = 2;</code>
     */
    public boolean hasAuthMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string AuthMsg = 2;</code>
     */
    public java.lang.String getAuthMsg() {
      java.lang.Object ref = authMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          authMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string AuthMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAuthMsgBytes() {
      java.lang.Object ref = authMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional fixed64 SessionID = 3;
    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionID_;
    /**
     * <code>optional fixed64 SessionID = 3;</code>
     */
    public boolean hasSessionID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional fixed64 SessionID = 3;</code>
     */
    public long getSessionID() {
      return sessionID_;
    }

    private void initFields() {
      authResult_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType.LoginSucceeded;
      authMsg_ = "";
      sessionID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAuthResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, authResult_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAuthMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFixed64(3, sessionID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, authResult_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAuthMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(3, sessionID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wisegeek.finance.protobuf.AuthenticationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wisegeek.finance.protobuf.Authentication.AuthenticationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.class, com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.Builder.class);
      }

      // Construct using com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        authResult_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType.LoginSucceeded;
        bitField0_ = (bitField0_ & ~0x00000001);
        authMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wisegeek.finance.protobuf.Authentication.internal_static_com_wisegeek_finance_protobuf_AuthenticationResponse_descriptor;
      }

      public com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse getDefaultInstanceForType() {
        return com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.getDefaultInstance();
      }

      public com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse build() {
        com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse buildPartial() {
        com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse result = new com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.authResult_ = authResult_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.authMsg_ = authMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionID_ = sessionID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse) {
          return mergeFrom((com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse other) {
        if (other == com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.getDefaultInstance()) return this;
        if (other.hasAuthResult()) {
          setAuthResult(other.getAuthResult());
        }
        if (other.hasAuthMsg()) {
          bitField0_ |= 0x00000002;
          authMsg_ = other.authMsg_;
          onChanged();
        }
        if (other.hasSessionID()) {
          setSessionID(other.getSessionID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAuthResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType AuthResult = 1;
      private com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType authResult_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType.LoginSucceeded;
      /**
       * <code>required .com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType AuthResult = 1;</code>
       */
      public boolean hasAuthResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType AuthResult = 1;</code>
       */
      public com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType getAuthResult() {
        return authResult_;
      }
      /**
       * <code>required .com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType AuthResult = 1;</code>
       */
      public Builder setAuthResult(com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        authResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.wisegeek.finance.protobuf.AuthenticationResponse.AuthResultType AuthResult = 1;</code>
       */
      public Builder clearAuthResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        authResult_ = com.wisegeek.finance.protobuf.Authentication.AuthenticationResponse.AuthResultType.LoginSucceeded;
        onChanged();
        return this;
      }

      // optional string AuthMsg = 2;
      private java.lang.Object authMsg_ = "";
      /**
       * <code>optional string AuthMsg = 2;</code>
       */
      public boolean hasAuthMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string AuthMsg = 2;</code>
       */
      public java.lang.String getAuthMsg() {
        java.lang.Object ref = authMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          authMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string AuthMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAuthMsgBytes() {
        java.lang.Object ref = authMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string AuthMsg = 2;</code>
       */
      public Builder setAuthMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        authMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string AuthMsg = 2;</code>
       */
      public Builder clearAuthMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        authMsg_ = getDefaultInstance().getAuthMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string AuthMsg = 2;</code>
       */
      public Builder setAuthMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        authMsg_ = value;
        onChanged();
        return this;
      }

      // optional fixed64 SessionID = 3;
      private long sessionID_ ;
      /**
       * <code>optional fixed64 SessionID = 3;</code>
       */
      public boolean hasSessionID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional fixed64 SessionID = 3;</code>
       */
      public long getSessionID() {
        return sessionID_;
      }
      /**
       * <code>optional fixed64 SessionID = 3;</code>
       */
      public Builder setSessionID(long value) {
        bitField0_ |= 0x00000004;
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 SessionID = 3;</code>
       */
      public Builder clearSessionID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wisegeek.finance.protobuf.AuthenticationResponse)
    }

    static {
      defaultInstance = new AuthenticationResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wisegeek.finance.protobuf.AuthenticationResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_TerminalInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_TerminalInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wisegeek_finance_protobuf_AuthenticationResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wisegeek_finance_protobuf_AuthenticationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024Authentication.proto\022\035com.wisegeek.fin" +
      "ance.protobuf\"\325\002\n\025AuthenticationRequest\022" +
      "\021\n\tLoginName\030\001 \002(\t\022\020\n\010Password\030\002 \002(\t\022T\n\005" +
      "Group\030\003 \001(\0162>.com.wisegeek.finance.proto" +
      "buf.AuthenticationRequest.UserGroup:\005GUE" +
      "ST\022S\n\010Terminal\030\004 \001(\0132A.com.wisegeek.fina" +
      "nce.protobuf.AuthenticationRequest.Termi" +
      "nalInfo\0324\n\014TerminalInfo\022\023\n\013MachineType\030\001" +
      " \002(\t\022\017\n\007Version\030\002 \001(\t\"6\n\tUserGroup\022\t\n\005GU" +
      "EST\020\000\022\013\n\007GENERAL\020\001\022\007\n\003VIP\020\002\022\010\n\004TEST\020\003\"\377\001",
      "\n\026AuthenticationResponse\022X\n\nAuthResult\030\001" +
      " \002(\0162D.com.wisegeek.finance.protobuf.Aut" +
      "henticationResponse.AuthResultType\022\017\n\007Au" +
      "thMsg\030\002 \001(\t\022\021\n\tSessionID\030\003 \001(\006\"g\n\016AuthRe" +
      "sultType\022\022\n\016LoginSucceeded\020\000\022 \n\034WrongPas" +
      "swordAccountNotExist\020\001\022\016\n\nServerBusy\020\002\022\017" +
      "\n\013UserLocking\020\003B/\n\035com.wisegeek.finance." +
      "protobufB\016Authentication"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_descriptor,
              new java.lang.String[] { "LoginName", "Password", "Group", "Terminal", });
          internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_TerminalInfo_descriptor =
            internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_descriptor.getNestedTypes().get(0);
          internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_TerminalInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wisegeek_finance_protobuf_AuthenticationRequest_TerminalInfo_descriptor,
              new java.lang.String[] { "MachineType", "Version", });
          internal_static_com_wisegeek_finance_protobuf_AuthenticationResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_wisegeek_finance_protobuf_AuthenticationResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wisegeek_finance_protobuf_AuthenticationResponse_descriptor,
              new java.lang.String[] { "AuthResult", "AuthMsg", "SessionID", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
