// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileTransfer.proto

package com.wisegeek.finance.protobuf;

public final class FileTransfer {
  private FileTransfer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FileTransferRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string FullName = 1;
    /**
     * <code>required string FullName = 1;</code>
     */
    boolean hasFullName();
    /**
     * <code>required string FullName = 1;</code>
     */
    java.lang.String getFullName();
    /**
     * <code>required string FullName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFullNameBytes();

    // optional fixed64 SessionID = 2;
    /**
     * <code>optional fixed64 SessionID = 2;</code>
     */
    boolean hasSessionID();
    /**
     * <code>optional fixed64 SessionID = 2;</code>
     */
    long getSessionID();
  }
  /**
   * Protobuf type {@code com.wisegeek.finance.protobuf.FileTransferRequest}
   */
  public static final class FileTransferRequest extends
      com.google.protobuf.GeneratedMessage
      implements FileTransferRequestOrBuilder {
    // Use FileTransferRequest.newBuilder() to construct.
    private FileTransferRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileTransferRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileTransferRequest defaultInstance;
    public static FileTransferRequest getDefaultInstance() {
      return defaultInstance;
    }

    public FileTransferRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileTransferRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fullName_ = input.readBytes();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              sessionID_ = input.readFixed64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wisegeek.finance.protobuf.FileTransfer.internal_static_com_wisegeek_finance_protobuf_FileTransferRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wisegeek.finance.protobuf.FileTransfer.internal_static_com_wisegeek_finance_protobuf_FileTransferRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest.class, com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<FileTransferRequest> PARSER =
        new com.google.protobuf.AbstractParser<FileTransferRequest>() {
      public FileTransferRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileTransferRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FileTransferRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string FullName = 1;
    public static final int FULLNAME_FIELD_NUMBER = 1;
    private java.lang.Object fullName_;
    /**
     * <code>required string FullName = 1;</code>
     */
    public boolean hasFullName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string FullName = 1;</code>
     */
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fullName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string FullName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional fixed64 SessionID = 2;
    public static final int SESSIONID_FIELD_NUMBER = 2;
    private long sessionID_;
    /**
     * <code>optional fixed64 SessionID = 2;</code>
     */
    public boolean hasSessionID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional fixed64 SessionID = 2;</code>
     */
    public long getSessionID() {
      return sessionID_;
    }

    private void initFields() {
      fullName_ = "";
      sessionID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFullName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFullNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, sessionID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFullNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, sessionID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wisegeek.finance.protobuf.FileTransferRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wisegeek.finance.protobuf.FileTransfer.internal_static_com_wisegeek_finance_protobuf_FileTransferRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wisegeek.finance.protobuf.FileTransfer.internal_static_com_wisegeek_finance_protobuf_FileTransferRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest.class, com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest.Builder.class);
      }

      // Construct using com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fullName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wisegeek.finance.protobuf.FileTransfer.internal_static_com_wisegeek_finance_protobuf_FileTransferRequest_descriptor;
      }

      public com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest getDefaultInstanceForType() {
        return com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest.getDefaultInstance();
      }

      public com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest build() {
        com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest buildPartial() {
        com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest result = new com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fullName_ = fullName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionID_ = sessionID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest) {
          return mergeFrom((com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest other) {
        if (other == com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest.getDefaultInstance()) return this;
        if (other.hasFullName()) {
          bitField0_ |= 0x00000001;
          fullName_ = other.fullName_;
          onChanged();
        }
        if (other.hasSessionID()) {
          setSessionID(other.getSessionID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFullName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wisegeek.finance.protobuf.FileTransfer.FileTransferRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string FullName = 1;
      private java.lang.Object fullName_ = "";
      /**
       * <code>required string FullName = 1;</code>
       */
      public boolean hasFullName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string FullName = 1;</code>
       */
      public java.lang.String getFullName() {
        java.lang.Object ref = fullName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fullName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string FullName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFullNameBytes() {
        java.lang.Object ref = fullName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string FullName = 1;</code>
       */
      public Builder setFullName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fullName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string FullName = 1;</code>
       */
      public Builder clearFullName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fullName_ = getDefaultInstance().getFullName();
        onChanged();
        return this;
      }
      /**
       * <code>required string FullName = 1;</code>
       */
      public Builder setFullNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fullName_ = value;
        onChanged();
        return this;
      }

      // optional fixed64 SessionID = 2;
      private long sessionID_ ;
      /**
       * <code>optional fixed64 SessionID = 2;</code>
       */
      public boolean hasSessionID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional fixed64 SessionID = 2;</code>
       */
      public long getSessionID() {
        return sessionID_;
      }
      /**
       * <code>optional fixed64 SessionID = 2;</code>
       */
      public Builder setSessionID(long value) {
        bitField0_ |= 0x00000002;
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 SessionID = 2;</code>
       */
      public Builder clearSessionID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wisegeek.finance.protobuf.FileTransferRequest)
    }

    static {
      defaultInstance = new FileTransferRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wisegeek.finance.protobuf.FileTransferRequest)
  }

  public interface FileTransferResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string FullName = 1;
    /**
     * <code>required string FullName = 1;</code>
     */
    boolean hasFullName();
    /**
     * <code>required string FullName = 1;</code>
     */
    java.lang.String getFullName();
    /**
     * <code>required string FullName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFullNameBytes();

    // required bool Exist = 2;
    /**
     * <code>required bool Exist = 2;</code>
     */
    boolean hasExist();
    /**
     * <code>required bool Exist = 2;</code>
     */
    boolean getExist();

    // optional string Value = 3;
    /**
     * <code>optional string Value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>optional string Value = 3;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string Value = 3;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code com.wisegeek.finance.protobuf.FileTransferResponse}
   */
  public static final class FileTransferResponse extends
      com.google.protobuf.GeneratedMessage
      implements FileTransferResponseOrBuilder {
    // Use FileTransferResponse.newBuilder() to construct.
    private FileTransferResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileTransferResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileTransferResponse defaultInstance;
    public static FileTransferResponse getDefaultInstance() {
      return defaultInstance;
    }

    public FileTransferResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileTransferResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fullName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              exist_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wisegeek.finance.protobuf.FileTransfer.internal_static_com_wisegeek_finance_protobuf_FileTransferResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wisegeek.finance.protobuf.FileTransfer.internal_static_com_wisegeek_finance_protobuf_FileTransferResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse.class, com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<FileTransferResponse> PARSER =
        new com.google.protobuf.AbstractParser<FileTransferResponse>() {
      public FileTransferResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileTransferResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FileTransferResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string FullName = 1;
    public static final int FULLNAME_FIELD_NUMBER = 1;
    private java.lang.Object fullName_;
    /**
     * <code>required string FullName = 1;</code>
     */
    public boolean hasFullName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string FullName = 1;</code>
     */
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fullName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string FullName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bool Exist = 2;
    public static final int EXIST_FIELD_NUMBER = 2;
    private boolean exist_;
    /**
     * <code>required bool Exist = 2;</code>
     */
    public boolean hasExist() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool Exist = 2;</code>
     */
    public boolean getExist() {
      return exist_;
    }

    // optional string Value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private java.lang.Object value_;
    /**
     * <code>optional string Value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string Value = 3;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      fullName_ = "";
      exist_ = false;
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFullName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExist()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFullNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, exist_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFullNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, exist_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wisegeek.finance.protobuf.FileTransferResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wisegeek.finance.protobuf.FileTransfer.internal_static_com_wisegeek_finance_protobuf_FileTransferResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wisegeek.finance.protobuf.FileTransfer.internal_static_com_wisegeek_finance_protobuf_FileTransferResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse.class, com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse.Builder.class);
      }

      // Construct using com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fullName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        exist_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wisegeek.finance.protobuf.FileTransfer.internal_static_com_wisegeek_finance_protobuf_FileTransferResponse_descriptor;
      }

      public com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse getDefaultInstanceForType() {
        return com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse.getDefaultInstance();
      }

      public com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse build() {
        com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse buildPartial() {
        com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse result = new com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fullName_ = fullName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.exist_ = exist_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse) {
          return mergeFrom((com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse other) {
        if (other == com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse.getDefaultInstance()) return this;
        if (other.hasFullName()) {
          bitField0_ |= 0x00000001;
          fullName_ = other.fullName_;
          onChanged();
        }
        if (other.hasExist()) {
          setExist(other.getExist());
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000004;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFullName()) {
          
          return false;
        }
        if (!hasExist()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wisegeek.finance.protobuf.FileTransfer.FileTransferResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string FullName = 1;
      private java.lang.Object fullName_ = "";
      /**
       * <code>required string FullName = 1;</code>
       */
      public boolean hasFullName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string FullName = 1;</code>
       */
      public java.lang.String getFullName() {
        java.lang.Object ref = fullName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fullName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string FullName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFullNameBytes() {
        java.lang.Object ref = fullName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string FullName = 1;</code>
       */
      public Builder setFullName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fullName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string FullName = 1;</code>
       */
      public Builder clearFullName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fullName_ = getDefaultInstance().getFullName();
        onChanged();
        return this;
      }
      /**
       * <code>required string FullName = 1;</code>
       */
      public Builder setFullNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fullName_ = value;
        onChanged();
        return this;
      }

      // required bool Exist = 2;
      private boolean exist_ ;
      /**
       * <code>required bool Exist = 2;</code>
       */
      public boolean hasExist() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool Exist = 2;</code>
       */
      public boolean getExist() {
        return exist_;
      }
      /**
       * <code>required bool Exist = 2;</code>
       */
      public Builder setExist(boolean value) {
        bitField0_ |= 0x00000002;
        exist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool Exist = 2;</code>
       */
      public Builder clearExist() {
        bitField0_ = (bitField0_ & ~0x00000002);
        exist_ = false;
        onChanged();
        return this;
      }

      // optional string Value = 3;
      private java.lang.Object value_ = "";
      /**
       * <code>optional string Value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string Value = 3;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Value = 3;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Value = 3;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Value = 3;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wisegeek.finance.protobuf.FileTransferResponse)
    }

    static {
      defaultInstance = new FileTransferResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wisegeek.finance.protobuf.FileTransferResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wisegeek_finance_protobuf_FileTransferRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wisegeek_finance_protobuf_FileTransferRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wisegeek_finance_protobuf_FileTransferResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wisegeek_finance_protobuf_FileTransferResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022FileTransfer.proto\022\035com.wisegeek.finan" +
      "ce.protobuf\":\n\023FileTransferRequest\022\020\n\010Fu" +
      "llName\030\001 \002(\t\022\021\n\tSessionID\030\002 \001(\006\"F\n\024FileT" +
      "ransferResponse\022\020\n\010FullName\030\001 \002(\t\022\r\n\005Exi" +
      "st\030\002 \002(\010\022\r\n\005Value\030\003 \001(\tB-\n\035com.wisegeek." +
      "finance.protobufB\014FileTransfer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wisegeek_finance_protobuf_FileTransferRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wisegeek_finance_protobuf_FileTransferRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wisegeek_finance_protobuf_FileTransferRequest_descriptor,
              new java.lang.String[] { "FullName", "SessionID", });
          internal_static_com_wisegeek_finance_protobuf_FileTransferResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_wisegeek_finance_protobuf_FileTransferResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wisegeek_finance_protobuf_FileTransferResponse_descriptor,
              new java.lang.String[] { "FullName", "Exist", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
