// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockExchangeDetail.proto

package com.wisegeek.finance.protobuf;

public final class StockExchangeDetail {
  private StockExchangeDetail() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StockExchangeDetailRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string StockCode = 1;
    /**
     * <code>required string StockCode = 1;</code>
     */
    boolean hasStockCode();
    /**
     * <code>required string StockCode = 1;</code>
     */
    java.lang.String getStockCode();
    /**
     * <code>required string StockCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getStockCodeBytes();

    // optional int32 DetailCount = 2 [default = 5];
    /**
     * <code>optional int32 DetailCount = 2 [default = 5];</code>
     */
    boolean hasDetailCount();
    /**
     * <code>optional int32 DetailCount = 2 [default = 5];</code>
     */
    int getDetailCount();

    // optional fixed64 SessionID = 3;
    /**
     * <code>optional fixed64 SessionID = 3;</code>
     */
    boolean hasSessionID();
    /**
     * <code>optional fixed64 SessionID = 3;</code>
     */
    long getSessionID();
  }
  /**
   * Protobuf type {@code com.wisegeek.finance.protobuf.StockExchangeDetailRequest}
   */
  public static final class StockExchangeDetailRequest extends
      com.google.protobuf.GeneratedMessage
      implements StockExchangeDetailRequestOrBuilder {
    // Use StockExchangeDetailRequest.newBuilder() to construct.
    private StockExchangeDetailRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StockExchangeDetailRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StockExchangeDetailRequest defaultInstance;
    public static StockExchangeDetailRequest getDefaultInstance() {
      return defaultInstance;
    }

    public StockExchangeDetailRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StockExchangeDetailRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              stockCode_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              detailCount_ = input.readInt32();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              sessionID_ = input.readFixed64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest.class, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<StockExchangeDetailRequest> PARSER =
        new com.google.protobuf.AbstractParser<StockExchangeDetailRequest>() {
      public StockExchangeDetailRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StockExchangeDetailRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StockExchangeDetailRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string StockCode = 1;
    public static final int STOCKCODE_FIELD_NUMBER = 1;
    private java.lang.Object stockCode_;
    /**
     * <code>required string StockCode = 1;</code>
     */
    public boolean hasStockCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string StockCode = 1;</code>
     */
    public java.lang.String getStockCode() {
      java.lang.Object ref = stockCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stockCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string StockCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStockCodeBytes() {
      java.lang.Object ref = stockCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 DetailCount = 2 [default = 5];
    public static final int DETAILCOUNT_FIELD_NUMBER = 2;
    private int detailCount_;
    /**
     * <code>optional int32 DetailCount = 2 [default = 5];</code>
     */
    public boolean hasDetailCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 DetailCount = 2 [default = 5];</code>
     */
    public int getDetailCount() {
      return detailCount_;
    }

    // optional fixed64 SessionID = 3;
    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionID_;
    /**
     * <code>optional fixed64 SessionID = 3;</code>
     */
    public boolean hasSessionID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional fixed64 SessionID = 3;</code>
     */
    public long getSessionID() {
      return sessionID_;
    }

    private void initFields() {
      stockCode_ = "";
      detailCount_ = 5;
      sessionID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStockCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStockCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, detailCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFixed64(3, sessionID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStockCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, detailCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(3, sessionID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wisegeek.finance.protobuf.StockExchangeDetailRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest.class, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest.Builder.class);
      }

      // Construct using com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stockCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        detailCount_ = 5;
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailRequest_descriptor;
      }

      public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest getDefaultInstanceForType() {
        return com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest.getDefaultInstance();
      }

      public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest build() {
        com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest buildPartial() {
        com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest result = new com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stockCode_ = stockCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.detailCount_ = detailCount_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionID_ = sessionID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest) {
          return mergeFrom((com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest other) {
        if (other == com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest.getDefaultInstance()) return this;
        if (other.hasStockCode()) {
          bitField0_ |= 0x00000001;
          stockCode_ = other.stockCode_;
          onChanged();
        }
        if (other.hasDetailCount()) {
          setDetailCount(other.getDetailCount());
        }
        if (other.hasSessionID()) {
          setSessionID(other.getSessionID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStockCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string StockCode = 1;
      private java.lang.Object stockCode_ = "";
      /**
       * <code>required string StockCode = 1;</code>
       */
      public boolean hasStockCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string StockCode = 1;</code>
       */
      public java.lang.String getStockCode() {
        java.lang.Object ref = stockCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          stockCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string StockCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStockCodeBytes() {
        java.lang.Object ref = stockCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string StockCode = 1;</code>
       */
      public Builder setStockCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stockCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string StockCode = 1;</code>
       */
      public Builder clearStockCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stockCode_ = getDefaultInstance().getStockCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string StockCode = 1;</code>
       */
      public Builder setStockCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stockCode_ = value;
        onChanged();
        return this;
      }

      // optional int32 DetailCount = 2 [default = 5];
      private int detailCount_ = 5;
      /**
       * <code>optional int32 DetailCount = 2 [default = 5];</code>
       */
      public boolean hasDetailCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 DetailCount = 2 [default = 5];</code>
       */
      public int getDetailCount() {
        return detailCount_;
      }
      /**
       * <code>optional int32 DetailCount = 2 [default = 5];</code>
       */
      public Builder setDetailCount(int value) {
        bitField0_ |= 0x00000002;
        detailCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 DetailCount = 2 [default = 5];</code>
       */
      public Builder clearDetailCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        detailCount_ = 5;
        onChanged();
        return this;
      }

      // optional fixed64 SessionID = 3;
      private long sessionID_ ;
      /**
       * <code>optional fixed64 SessionID = 3;</code>
       */
      public boolean hasSessionID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional fixed64 SessionID = 3;</code>
       */
      public long getSessionID() {
        return sessionID_;
      }
      /**
       * <code>optional fixed64 SessionID = 3;</code>
       */
      public Builder setSessionID(long value) {
        bitField0_ |= 0x00000004;
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 SessionID = 3;</code>
       */
      public Builder clearSessionID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wisegeek.finance.protobuf.StockExchangeDetailRequest)
    }

    static {
      defaultInstance = new StockExchangeDetailRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wisegeek.finance.protobuf.StockExchangeDetailRequest)
  }

  public interface StockExchangeDetailResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string StockCode = 1;
    /**
     * <code>required string StockCode = 1;</code>
     */
    boolean hasStockCode();
    /**
     * <code>required string StockCode = 1;</code>
     */
    java.lang.String getStockCode();
    /**
     * <code>required string StockCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getStockCodeBytes();

    // repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;
    /**
     * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
     */
    java.util.List<com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail> 
        getExchangeDetailsList();
    /**
     * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
     */
    com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail getExchangeDetails(int index);
    /**
     * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
     */
    int getExchangeDetailsCount();
    /**
     * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
     */
    java.util.List<? extends com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetailOrBuilder> 
        getExchangeDetailsOrBuilderList();
    /**
     * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
     */
    com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetailOrBuilder getExchangeDetailsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.wisegeek.finance.protobuf.StockExchangeDetailResponse}
   */
  public static final class StockExchangeDetailResponse extends
      com.google.protobuf.GeneratedMessage
      implements StockExchangeDetailResponseOrBuilder {
    // Use StockExchangeDetailResponse.newBuilder() to construct.
    private StockExchangeDetailResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StockExchangeDetailResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StockExchangeDetailResponse defaultInstance;
    public static StockExchangeDetailResponse getDefaultInstance() {
      return defaultInstance;
    }

    public StockExchangeDetailResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StockExchangeDetailResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              stockCode_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                exchangeDetails_ = new java.util.ArrayList<com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail>();
                mutable_bitField0_ |= 0x00000002;
              }
              exchangeDetails_.add(input.readMessage(com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          exchangeDetails_ = java.util.Collections.unmodifiableList(exchangeDetails_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.class, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<StockExchangeDetailResponse> PARSER =
        new com.google.protobuf.AbstractParser<StockExchangeDetailResponse>() {
      public StockExchangeDetailResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StockExchangeDetailResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StockExchangeDetailResponse> getParserForType() {
      return PARSER;
    }

    public interface ExchangeDetailOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string ExchName = 1;
      /**
       * <code>optional string ExchName = 1;</code>
       */
      boolean hasExchName();
      /**
       * <code>optional string ExchName = 1;</code>
       */
      java.lang.String getExchName();
      /**
       * <code>optional string ExchName = 1;</code>
       */
      com.google.protobuf.ByteString
          getExchNameBytes();

      // optional fixed64 BidPrice = 2;
      /**
       * <code>optional fixed64 BidPrice = 2;</code>
       */
      boolean hasBidPrice();
      /**
       * <code>optional fixed64 BidPrice = 2;</code>
       */
      long getBidPrice();

      // optional fixed64 AskPrice = 3;
      /**
       * <code>optional fixed64 AskPrice = 3;</code>
       */
      boolean hasAskPrice();
      /**
       * <code>optional fixed64 AskPrice = 3;</code>
       */
      long getAskPrice();

      // optional fixed64 TradePrice = 4;
      /**
       * <code>optional fixed64 TradePrice = 4;</code>
       */
      boolean hasTradePrice();
      /**
       * <code>optional fixed64 TradePrice = 4;</code>
       */
      long getTradePrice();

      // optional int32 Offset = 5;
      /**
       * <code>optional int32 Offset = 5;</code>
       */
      boolean hasOffset();
      /**
       * <code>optional int32 Offset = 5;</code>
       */
      int getOffset();

      // optional fixed64 LastTime = 6;
      /**
       * <code>optional fixed64 LastTime = 6;</code>
       */
      boolean hasLastTime();
      /**
       * <code>optional fixed64 LastTime = 6;</code>
       */
      long getLastTime();
    }
    /**
     * Protobuf type {@code com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail}
     */
    public static final class ExchangeDetail extends
        com.google.protobuf.GeneratedMessage
        implements ExchangeDetailOrBuilder {
      // Use ExchangeDetail.newBuilder() to construct.
      private ExchangeDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private ExchangeDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final ExchangeDetail defaultInstance;
      public static ExchangeDetail getDefaultInstance() {
        return defaultInstance;
      }

      public ExchangeDetail getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private ExchangeDetail(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                exchName_ = input.readBytes();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                bidPrice_ = input.readFixed64();
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                askPrice_ = input.readFixed64();
                break;
              }
              case 33: {
                bitField0_ |= 0x00000008;
                tradePrice_ = input.readFixed64();
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                offset_ = input.readInt32();
                break;
              }
              case 49: {
                bitField0_ |= 0x00000020;
                lastTime_ = input.readFixed64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_ExchangeDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_ExchangeDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.class, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder.class);
      }

      public static com.google.protobuf.Parser<ExchangeDetail> PARSER =
          new com.google.protobuf.AbstractParser<ExchangeDetail>() {
        public ExchangeDetail parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ExchangeDetail(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ExchangeDetail> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string ExchName = 1;
      public static final int EXCHNAME_FIELD_NUMBER = 1;
      private java.lang.Object exchName_;
      /**
       * <code>optional string ExchName = 1;</code>
       */
      public boolean hasExchName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string ExchName = 1;</code>
       */
      public java.lang.String getExchName() {
        java.lang.Object ref = exchName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exchName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string ExchName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getExchNameBytes() {
        java.lang.Object ref = exchName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional fixed64 BidPrice = 2;
      public static final int BIDPRICE_FIELD_NUMBER = 2;
      private long bidPrice_;
      /**
       * <code>optional fixed64 BidPrice = 2;</code>
       */
      public boolean hasBidPrice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional fixed64 BidPrice = 2;</code>
       */
      public long getBidPrice() {
        return bidPrice_;
      }

      // optional fixed64 AskPrice = 3;
      public static final int ASKPRICE_FIELD_NUMBER = 3;
      private long askPrice_;
      /**
       * <code>optional fixed64 AskPrice = 3;</code>
       */
      public boolean hasAskPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional fixed64 AskPrice = 3;</code>
       */
      public long getAskPrice() {
        return askPrice_;
      }

      // optional fixed64 TradePrice = 4;
      public static final int TRADEPRICE_FIELD_NUMBER = 4;
      private long tradePrice_;
      /**
       * <code>optional fixed64 TradePrice = 4;</code>
       */
      public boolean hasTradePrice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional fixed64 TradePrice = 4;</code>
       */
      public long getTradePrice() {
        return tradePrice_;
      }

      // optional int32 Offset = 5;
      public static final int OFFSET_FIELD_NUMBER = 5;
      private int offset_;
      /**
       * <code>optional int32 Offset = 5;</code>
       */
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 Offset = 5;</code>
       */
      public int getOffset() {
        return offset_;
      }

      // optional fixed64 LastTime = 6;
      public static final int LASTTIME_FIELD_NUMBER = 6;
      private long lastTime_;
      /**
       * <code>optional fixed64 LastTime = 6;</code>
       */
      public boolean hasLastTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional fixed64 LastTime = 6;</code>
       */
      public long getLastTime() {
        return lastTime_;
      }

      private void initFields() {
        exchName_ = "";
        bidPrice_ = 0L;
        askPrice_ = 0L;
        tradePrice_ = 0L;
        offset_ = 0;
        lastTime_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getExchNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFixed64(2, bidPrice_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeFixed64(3, askPrice_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeFixed64(4, tradePrice_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeInt32(5, offset_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeFixed64(6, lastTime_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getExchNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFixed64Size(2, bidPrice_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFixed64Size(3, askPrice_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFixed64Size(4, tradePrice_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, offset_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFixed64Size(6, lastTime_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetailOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_ExchangeDetail_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_ExchangeDetail_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.class, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder.class);
        }

        // Construct using com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          exchName_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          bidPrice_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          askPrice_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          tradePrice_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000008);
          offset_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          lastTime_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_ExchangeDetail_descriptor;
        }

        public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail getDefaultInstanceForType() {
          return com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.getDefaultInstance();
        }

        public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail build() {
          com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail buildPartial() {
          com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail result = new com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.exchName_ = exchName_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.bidPrice_ = bidPrice_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.askPrice_ = askPrice_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.tradePrice_ = tradePrice_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.offset_ = offset_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.lastTime_ = lastTime_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail) {
            return mergeFrom((com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail other) {
          if (other == com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.getDefaultInstance()) return this;
          if (other.hasExchName()) {
            bitField0_ |= 0x00000001;
            exchName_ = other.exchName_;
            onChanged();
          }
          if (other.hasBidPrice()) {
            setBidPrice(other.getBidPrice());
          }
          if (other.hasAskPrice()) {
            setAskPrice(other.getAskPrice());
          }
          if (other.hasTradePrice()) {
            setTradePrice(other.getTradePrice());
          }
          if (other.hasOffset()) {
            setOffset(other.getOffset());
          }
          if (other.hasLastTime()) {
            setLastTime(other.getLastTime());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string ExchName = 1;
        private java.lang.Object exchName_ = "";
        /**
         * <code>optional string ExchName = 1;</code>
         */
        public boolean hasExchName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string ExchName = 1;</code>
         */
        public java.lang.String getExchName() {
          java.lang.Object ref = exchName_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            exchName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string ExchName = 1;</code>
         */
        public com.google.protobuf.ByteString
            getExchNameBytes() {
          java.lang.Object ref = exchName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            exchName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string ExchName = 1;</code>
         */
        public Builder setExchName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          exchName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string ExchName = 1;</code>
         */
        public Builder clearExchName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          exchName_ = getDefaultInstance().getExchName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string ExchName = 1;</code>
         */
        public Builder setExchNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          exchName_ = value;
          onChanged();
          return this;
        }

        // optional fixed64 BidPrice = 2;
        private long bidPrice_ ;
        /**
         * <code>optional fixed64 BidPrice = 2;</code>
         */
        public boolean hasBidPrice() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional fixed64 BidPrice = 2;</code>
         */
        public long getBidPrice() {
          return bidPrice_;
        }
        /**
         * <code>optional fixed64 BidPrice = 2;</code>
         */
        public Builder setBidPrice(long value) {
          bitField0_ |= 0x00000002;
          bidPrice_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional fixed64 BidPrice = 2;</code>
         */
        public Builder clearBidPrice() {
          bitField0_ = (bitField0_ & ~0x00000002);
          bidPrice_ = 0L;
          onChanged();
          return this;
        }

        // optional fixed64 AskPrice = 3;
        private long askPrice_ ;
        /**
         * <code>optional fixed64 AskPrice = 3;</code>
         */
        public boolean hasAskPrice() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional fixed64 AskPrice = 3;</code>
         */
        public long getAskPrice() {
          return askPrice_;
        }
        /**
         * <code>optional fixed64 AskPrice = 3;</code>
         */
        public Builder setAskPrice(long value) {
          bitField0_ |= 0x00000004;
          askPrice_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional fixed64 AskPrice = 3;</code>
         */
        public Builder clearAskPrice() {
          bitField0_ = (bitField0_ & ~0x00000004);
          askPrice_ = 0L;
          onChanged();
          return this;
        }

        // optional fixed64 TradePrice = 4;
        private long tradePrice_ ;
        /**
         * <code>optional fixed64 TradePrice = 4;</code>
         */
        public boolean hasTradePrice() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional fixed64 TradePrice = 4;</code>
         */
        public long getTradePrice() {
          return tradePrice_;
        }
        /**
         * <code>optional fixed64 TradePrice = 4;</code>
         */
        public Builder setTradePrice(long value) {
          bitField0_ |= 0x00000008;
          tradePrice_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional fixed64 TradePrice = 4;</code>
         */
        public Builder clearTradePrice() {
          bitField0_ = (bitField0_ & ~0x00000008);
          tradePrice_ = 0L;
          onChanged();
          return this;
        }

        // optional int32 Offset = 5;
        private int offset_ ;
        /**
         * <code>optional int32 Offset = 5;</code>
         */
        public boolean hasOffset() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional int32 Offset = 5;</code>
         */
        public int getOffset() {
          return offset_;
        }
        /**
         * <code>optional int32 Offset = 5;</code>
         */
        public Builder setOffset(int value) {
          bitField0_ |= 0x00000010;
          offset_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 Offset = 5;</code>
         */
        public Builder clearOffset() {
          bitField0_ = (bitField0_ & ~0x00000010);
          offset_ = 0;
          onChanged();
          return this;
        }

        // optional fixed64 LastTime = 6;
        private long lastTime_ ;
        /**
         * <code>optional fixed64 LastTime = 6;</code>
         */
        public boolean hasLastTime() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional fixed64 LastTime = 6;</code>
         */
        public long getLastTime() {
          return lastTime_;
        }
        /**
         * <code>optional fixed64 LastTime = 6;</code>
         */
        public Builder setLastTime(long value) {
          bitField0_ |= 0x00000020;
          lastTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional fixed64 LastTime = 6;</code>
         */
        public Builder clearLastTime() {
          bitField0_ = (bitField0_ & ~0x00000020);
          lastTime_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail)
      }

      static {
        defaultInstance = new ExchangeDetail(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail)
    }

    private int bitField0_;
    // required string StockCode = 1;
    public static final int STOCKCODE_FIELD_NUMBER = 1;
    private java.lang.Object stockCode_;
    /**
     * <code>required string StockCode = 1;</code>
     */
    public boolean hasStockCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string StockCode = 1;</code>
     */
    public java.lang.String getStockCode() {
      java.lang.Object ref = stockCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stockCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string StockCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStockCodeBytes() {
      java.lang.Object ref = stockCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;
    public static final int EXCHANGEDETAILS_FIELD_NUMBER = 2;
    private java.util.List<com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail> exchangeDetails_;
    /**
     * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
     */
    public java.util.List<com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail> getExchangeDetailsList() {
      return exchangeDetails_;
    }
    /**
     * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
     */
    public java.util.List<? extends com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetailOrBuilder> 
        getExchangeDetailsOrBuilderList() {
      return exchangeDetails_;
    }
    /**
     * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
     */
    public int getExchangeDetailsCount() {
      return exchangeDetails_.size();
    }
    /**
     * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
     */
    public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail getExchangeDetails(int index) {
      return exchangeDetails_.get(index);
    }
    /**
     * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
     */
    public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetailOrBuilder getExchangeDetailsOrBuilder(
        int index) {
      return exchangeDetails_.get(index);
    }

    private void initFields() {
      stockCode_ = "";
      exchangeDetails_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStockCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStockCodeBytes());
      }
      for (int i = 0; i < exchangeDetails_.size(); i++) {
        output.writeMessage(2, exchangeDetails_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStockCodeBytes());
      }
      for (int i = 0; i < exchangeDetails_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, exchangeDetails_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wisegeek.finance.protobuf.StockExchangeDetailResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.class, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.Builder.class);
      }

      // Construct using com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExchangeDetailsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stockCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (exchangeDetailsBuilder_ == null) {
          exchangeDetails_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          exchangeDetailsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wisegeek.finance.protobuf.StockExchangeDetail.internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_descriptor;
      }

      public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse getDefaultInstanceForType() {
        return com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.getDefaultInstance();
      }

      public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse build() {
        com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse buildPartial() {
        com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse result = new com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stockCode_ = stockCode_;
        if (exchangeDetailsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            exchangeDetails_ = java.util.Collections.unmodifiableList(exchangeDetails_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.exchangeDetails_ = exchangeDetails_;
        } else {
          result.exchangeDetails_ = exchangeDetailsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse) {
          return mergeFrom((com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse other) {
        if (other == com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.getDefaultInstance()) return this;
        if (other.hasStockCode()) {
          bitField0_ |= 0x00000001;
          stockCode_ = other.stockCode_;
          onChanged();
        }
        if (exchangeDetailsBuilder_ == null) {
          if (!other.exchangeDetails_.isEmpty()) {
            if (exchangeDetails_.isEmpty()) {
              exchangeDetails_ = other.exchangeDetails_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureExchangeDetailsIsMutable();
              exchangeDetails_.addAll(other.exchangeDetails_);
            }
            onChanged();
          }
        } else {
          if (!other.exchangeDetails_.isEmpty()) {
            if (exchangeDetailsBuilder_.isEmpty()) {
              exchangeDetailsBuilder_.dispose();
              exchangeDetailsBuilder_ = null;
              exchangeDetails_ = other.exchangeDetails_;
              bitField0_ = (bitField0_ & ~0x00000002);
              exchangeDetailsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExchangeDetailsFieldBuilder() : null;
            } else {
              exchangeDetailsBuilder_.addAllMessages(other.exchangeDetails_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStockCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string StockCode = 1;
      private java.lang.Object stockCode_ = "";
      /**
       * <code>required string StockCode = 1;</code>
       */
      public boolean hasStockCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string StockCode = 1;</code>
       */
      public java.lang.String getStockCode() {
        java.lang.Object ref = stockCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          stockCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string StockCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStockCodeBytes() {
        java.lang.Object ref = stockCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string StockCode = 1;</code>
       */
      public Builder setStockCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stockCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string StockCode = 1;</code>
       */
      public Builder clearStockCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stockCode_ = getDefaultInstance().getStockCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string StockCode = 1;</code>
       */
      public Builder setStockCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stockCode_ = value;
        onChanged();
        return this;
      }

      // repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;
      private java.util.List<com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail> exchangeDetails_ =
        java.util.Collections.emptyList();
      private void ensureExchangeDetailsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          exchangeDetails_ = new java.util.ArrayList<com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail>(exchangeDetails_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetailOrBuilder> exchangeDetailsBuilder_;

      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public java.util.List<com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail> getExchangeDetailsList() {
        if (exchangeDetailsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(exchangeDetails_);
        } else {
          return exchangeDetailsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public int getExchangeDetailsCount() {
        if (exchangeDetailsBuilder_ == null) {
          return exchangeDetails_.size();
        } else {
          return exchangeDetailsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail getExchangeDetails(int index) {
        if (exchangeDetailsBuilder_ == null) {
          return exchangeDetails_.get(index);
        } else {
          return exchangeDetailsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public Builder setExchangeDetails(
          int index, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail value) {
        if (exchangeDetailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExchangeDetailsIsMutable();
          exchangeDetails_.set(index, value);
          onChanged();
        } else {
          exchangeDetailsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public Builder setExchangeDetails(
          int index, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder builderForValue) {
        if (exchangeDetailsBuilder_ == null) {
          ensureExchangeDetailsIsMutable();
          exchangeDetails_.set(index, builderForValue.build());
          onChanged();
        } else {
          exchangeDetailsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public Builder addExchangeDetails(com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail value) {
        if (exchangeDetailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExchangeDetailsIsMutable();
          exchangeDetails_.add(value);
          onChanged();
        } else {
          exchangeDetailsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public Builder addExchangeDetails(
          int index, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail value) {
        if (exchangeDetailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExchangeDetailsIsMutable();
          exchangeDetails_.add(index, value);
          onChanged();
        } else {
          exchangeDetailsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public Builder addExchangeDetails(
          com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder builderForValue) {
        if (exchangeDetailsBuilder_ == null) {
          ensureExchangeDetailsIsMutable();
          exchangeDetails_.add(builderForValue.build());
          onChanged();
        } else {
          exchangeDetailsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public Builder addExchangeDetails(
          int index, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder builderForValue) {
        if (exchangeDetailsBuilder_ == null) {
          ensureExchangeDetailsIsMutable();
          exchangeDetails_.add(index, builderForValue.build());
          onChanged();
        } else {
          exchangeDetailsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public Builder addAllExchangeDetails(
          java.lang.Iterable<? extends com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail> values) {
        if (exchangeDetailsBuilder_ == null) {
          ensureExchangeDetailsIsMutable();
          super.addAll(values, exchangeDetails_);
          onChanged();
        } else {
          exchangeDetailsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public Builder clearExchangeDetails() {
        if (exchangeDetailsBuilder_ == null) {
          exchangeDetails_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          exchangeDetailsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public Builder removeExchangeDetails(int index) {
        if (exchangeDetailsBuilder_ == null) {
          ensureExchangeDetailsIsMutable();
          exchangeDetails_.remove(index);
          onChanged();
        } else {
          exchangeDetailsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder getExchangeDetailsBuilder(
          int index) {
        return getExchangeDetailsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetailOrBuilder getExchangeDetailsOrBuilder(
          int index) {
        if (exchangeDetailsBuilder_ == null) {
          return exchangeDetails_.get(index);  } else {
          return exchangeDetailsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public java.util.List<? extends com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetailOrBuilder> 
           getExchangeDetailsOrBuilderList() {
        if (exchangeDetailsBuilder_ != null) {
          return exchangeDetailsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(exchangeDetails_);
        }
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder addExchangeDetailsBuilder() {
        return getExchangeDetailsFieldBuilder().addBuilder(
            com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder addExchangeDetailsBuilder(
          int index) {
        return getExchangeDetailsFieldBuilder().addBuilder(
            index, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.wisegeek.finance.protobuf.StockExchangeDetailResponse.ExchangeDetail ExchangeDetails = 2;</code>
       */
      public java.util.List<com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder> 
           getExchangeDetailsBuilderList() {
        return getExchangeDetailsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetailOrBuilder> 
          getExchangeDetailsFieldBuilder() {
        if (exchangeDetailsBuilder_ == null) {
          exchangeDetailsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetail.Builder, com.wisegeek.finance.protobuf.StockExchangeDetail.StockExchangeDetailResponse.ExchangeDetailOrBuilder>(
                  exchangeDetails_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          exchangeDetails_ = null;
        }
        return exchangeDetailsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.wisegeek.finance.protobuf.StockExchangeDetailResponse)
    }

    static {
      defaultInstance = new StockExchangeDetailResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wisegeek.finance.protobuf.StockExchangeDetailResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_ExchangeDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_ExchangeDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031StockExchangeDetail.proto\022\035com.wisegee" +
      "k.finance.protobuf\"Z\n\032StockExchangeDetai" +
      "lRequest\022\021\n\tStockCode\030\001 \002(\t\022\026\n\013DetailCou" +
      "nt\030\002 \001(\005:\0015\022\021\n\tSessionID\030\003 \001(\006\"\222\002\n\033Stock" +
      "ExchangeDetailResponse\022\021\n\tStockCode\030\001 \002(" +
      "\t\022b\n\017ExchangeDetails\030\002 \003(\0132I.com.wisegee" +
      "k.finance.protobuf.StockExchangeDetailRe" +
      "sponse.ExchangeDetail\032|\n\016ExchangeDetail\022" +
      "\020\n\010ExchName\030\001 \001(\t\022\020\n\010BidPrice\030\002 \001(\006\022\020\n\010A" +
      "skPrice\030\003 \001(\006\022\022\n\nTradePrice\030\004 \001(\006\022\016\n\006Off",
      "set\030\005 \001(\005\022\020\n\010LastTime\030\006 \001(\006B4\n\035com.wiseg" +
      "eek.finance.protobufB\023StockExchangeDetai" +
      "l"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailRequest_descriptor,
              new java.lang.String[] { "StockCode", "DetailCount", "SessionID", });
          internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_descriptor,
              new java.lang.String[] { "StockCode", "ExchangeDetails", });
          internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_ExchangeDetail_descriptor =
            internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_descriptor.getNestedTypes().get(0);
          internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_ExchangeDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wisegeek_finance_protobuf_StockExchangeDetailResponse_ExchangeDetail_descriptor,
              new java.lang.String[] { "ExchName", "BidPrice", "AskPrice", "TradePrice", "Offset", "LastTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
